#!/bin/bash

# We presume that /arteria/arteria-{lib,packs,provisioning}
# have been mounted from the host when running this container

set -e

# Start the supervisord
service supervisord restart

# Install the runfolder package
cd /arteria/arteria-provisioning/services
./install-service runfolder root root dev /arteria/arteria-lib/runfolder /arteria/arteria-lib/arteria /opt/runfolder

# Install the siswrap package
cd /arteria/arteria-lib/siswrap/scripts/
./install
