---
- name: packages | Make temp directory
  file:
    path: /tmp/st2/{{ _st2_version }}/debs/{{ _st2_revision }}
    state: directory
  tags: [st2, packages]

- name: packages | Download
  get_url:
    url: "https://downloads.stackstorm.net/releases/st2/{{ _st2_version }}/debs/{{ _st2_revision }}/{{ item }}_{{ _st2_version }}-{{ _st2_revision }}_amd64.deb"
    dest: /tmp/st2/{{ _st2_version }}/debs/{{ _st2_revision }}/{{ item }}_{{ _st2_version }}-{{ _st2_revision }}_amd64.deb
  with_items: st2_packages
  register: package_files
  tags: [st2, packages]

- name: packages | Install
  sudo: true
  apt:
    deb: "{{ item.dest }}"
    force: yes
    state: present
  with_items: package_files.results
  tags: [st2, packages]
