# Create upstart scripts for st2 components
---
- name: upstart | Create init configs from templates
  sudo: true
  template:
    src: "{{ item }}"
    dest: "/etc/init/{{ item | basename | regex_replace('.j2', '.conf') }}"
    mode: 0644
    group: root
    group: root
  when: (item | dirname | basename) in st2_packages
  with_fileglob:
    - ../templates/*/*.j2
  register: init_configs
  tags: [st2, upstart]

- name: upstart | Create st2actionrunner workers
  sudo: true
  template:
    src: st2actions/st2actionrunner-worker.conf
    dest: "/etc/init/st2actionrunner-{{ item }}.conf"
    mode: 0644
    group: root
    group: root
  with_sequence: count="{{ st2_action_runners }}"
  when: "'st2actions' in st2_packages"
  tags: [st2, upstart]

- name: upstart | Create list of st2 services
  set_fact:
    st2_services: "{{ init_configs.results | selectattr('item', 'defined') | map(attribute='item') |
                  map('basename') | map('regex_replace', '.j2', '') | list() }}"
  tags: [st2, upstart]

- name: upstart | Enable st2 init services
  sudo: true
  service:
    name: "{{ item }}"
    enabled: yes
  with_items: st2_services
  notify:
    - restart st2
  tags: [st2, upstart]
