#!/bin/bash

set -e

if ! vagrant plugin list | grep --quiet vagrant-hostmanager; then 
    echo "The vagrant package vagrant-hostmanager is missing"
    vagrant plugin install vagrant-hostmanager
else
    echo "vagrant-hostmanager is already installed"
fi 

