#!/bin/bash

set -e

if ! vagrant plugin list | grep --quiet vagrant-hostmanager; then 
    echo "The vagrant package vagrant-hostmanager is missing"
    vagrant plugin install vagrant-hostmanager
else
    echo "vagrant-hostmanager is already installed"
fi 

if [ ! -f 'private_key' ]; then
  echo 'Generating ssh key'
  ssh-keygen -f private_key -C 'arteria' -P ''
fi

ansible_version=`ansible --version | head -n 1 | awk '{ print $2 }'`

if [ "$ansible_version" != "1.9.3" ]; then
  echo "You are running version '$ansible_version' of Ansible. This version has not been tested."
  exit 1
else
  echo "You are running a version of Ansible that has been tested ($ansible_version)"
fi
