#!/bin/bash

function abort()
{
  echo -e "\e[31mAn error occurred while validating\e[0m" >&2
  exit 1
}

trap 'abort' 0
set -e

echo "*******************************"
echo "* stackstorm"
echo "*******************************"

nc -zv stackstorm-master 8080
nc -zv stackstorm-master 9100
nc -zv stackstorm-master 9101

# Check if all expected services are running:
./stackstorm-up.py stackstorm-master vagrant

echo "*******************************"
echo "* services"
echo "*******************************"
nc -zv testarteria1 10700
nc -zv testarteria1 10800
nc -zv testarteria1 10900

trap : 0
echo "No validation errors"
