---

#TODO Ensure all this is versioned!

- name: install illumina bcl2fastq
  yum:
    name: http://support.illumina.com/content/dam/illumina-support/documents/downloads/software/bcl2fastq/bcl2fastq2-v2.17.1.14-Linux-x86_64.rpm
    state: present

- name: get arteria-bcl2fastq from github
  git:
    repo: https://github.com/arteria-project/arteria-bcl2fastq.git
    dest: /usr/src/arteria-bcl2fastq

- name: install arteria-bcl2fastq requirements
  pip:
      requirements: /usr/src/arteria-bcl2fastq/requirements/dev
      chdir: /usr/src/arteria-bcl2fastq
      virtualenv: "{{ arteria_bcl2fastq_env_root }}"
      virtualenv_command: /usr/local/bin/virtualenv
      state: present
      executable: "{{ arteria_bcl2fastq_env_root }}/bin/pip"

- name: install arteria-bcl2fastq
  pip:
      name: .
      chdir: /usr/src/arteria-bcl2fastq
      virtualenv: "{{ arteria_bcl2fastq_env_root }}"
      virtualenv_command: /usr/local/bin/virtualenv
      state: present
      executable: "{{ arteria_bcl2fastq_env_root }}/bin/pip"

- name: ensure bcl2fastq log dir exists
  file:
    state: directory
    path: "{{ bcl2fastq_logs_path }}"
    owner: "{{ arteria_user }}"

- name: ensure /etc/arteria/bcl2fastq dir exists
  file:
    state: directory
    path: "{{ arteria_bcl2fastq_config_root}}"

- name: place arteria-bcl2fastq config file in "{{ arteria_bcl2fastq_app_config }}"
  template:
    src: bcl2fastq_app.config.j2
    dest: "{{ arteria_bcl2fastq_app_config }}"

- name: place arteria-bcl2fastq config file in "{{ arteria_bcl2fastq_logger_config }}"
  template:
    src: bcl2fastq_logger.config.j2
    dest: "{{ arteria_bcl2fastq_logger_config }}"

- name: deploy arteria-bcl2fastq supervisord config
  template:
    src: supervisor_arteria_bcl2fastq.conf.j2
    dest: /etc/supervisor/conf.d/bcl2fastq.conf

- supervisorctl:
    name: bcl2fastq-ws
    state: restarted
    supervisorctl_path: /usr/local/bin/supervisorctl

# TODO: Make this prettier
- name: create bcl2fastq-ws-test for easy integration testing
  command: bash -c "echo 'source {{ arteria_bcl2fastq_env_root }}/bin/activate' > /usr/local/bin/bcl2fastq-ws-test && echo 'nosetests /arteria/arteria-bcl2fastq/tests/integration' >> /usr/local/bin/bcl2fastq-ws-test && chmod +x /usr/local/bin/bcl2fastq-ws-test"

- name: running integration tests for bcl2fastq...
  shell: sleep 2 && /usr/local/bin/bcl2fastq-ws-test
  ignore_errors: true
