---
- name: Install st2 for arteria
  remote_user: vagrant
  sudo: true
  hosts: master
  vars:
    # the StackStorm version to install
    version: 0.11.2
  roles:
    - local_st2mods # Do some local modifications for St2 to work
    - st2op
    - mongodb
    - rabbitmq
    - role: st2packages
      packages:
        - st2common
        - st2actions
        - st2api
        - st2auth
        - st2client
        - st2debug
        - st2reactor
    - mysql
    - mistral
    - st2web
    - arteria

- name: Setup the testarteria1 node
  remote_user: vagrant
  sudo: true
  hosts: nodes
  roles:
    - arteria_node
