---
- name: Install st2 for arteria
  remote_user: vagrant
  sudo: true
  hosts: master
  vars:
    # the StackStorm version to install
    version: stable   # TODO
  roles:
    - mongodb
    - rabbitmq
    - mysql
    - mistral
    - st2
    - arteria

- name: Setup the testarteria1 node
  remote_user: vagrant
  sudo: true
  hosts: nodes
  roles:
    - arteria_node

