---
- name: Install st2 for arteria
  hosts: master
  vars:
    st2_version: 0.13.2
  roles:
    - mongodb
    - rabbitmq
    - mysql
    - mistral
    - st2
    - st2web
    - arteria

- name: Setup the testarteria1 node
  remote_user: vagrant
  sudo: true
  hosts: nodes
  roles:
    - arteria_node

