#!/bin/bash

# Example how to run the arteria services docker image
#
# We need to mount the source code from the host to e.g. be able to
# install the services easily.

set -e

CONTAINER_NAME="artplay"
MOUNT_ROOT="~/repod/arteria/"
MOUNTS="-v $MOUNT_ROOT/arteria-packs:/arteria/arteria-packs:ro -v $MOUNT_ROOT/arteria-lib:/arteria/arteria-lib:ro -v $MOUNT_ROOT/arteria-provisioning:/arteria/arteria-provisioning:ro"
PORTS="-p 10900:10900 -p 10800:10800 -p 8888:8888"
IMAGE_VERSION=1
IMAGE_NAME="arteria/services:$IMAGE_VERSION"
ENTRY_POINT=""

if [ -z $1 ] ; then
    echo "Need to supply an argument: install, daemon, interactive"
    exit 1
fi

# Run the installation script that exists on the image
if [[ $1 == "install" ]]; then
    MODE="-a STDOUT -a STDERR"
    ENTRY_POINT="/root/install_services"
# Run the container in daemon mode; requires that the
# services are registered with supervisord
elif [[ $1 == "daemon" ]]; then
    MODE="-d"
# Else we spawn an interactive session in the container
else
    MODE="-t -i -w /root/" # --rm=true
    ENTRY_POINT="/bin/bash"
fi

docker run $MODE $PORTS --name $CONTAINER_NAME $MOUNTS $IMAGE_NAME $ENTRY_POINT

# If the container is already running and you're trying to enter it again
# then you need to first do a "docker start foo" followed by "docker attach foo"
# Remove it with "docker rm foo", or add "--rm=true" to your run command.
