---

- debug: msg="Arteria user in sisyphus={{ arteria_user }}"

- name: install sisyphus dependencies from centos repository
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - dos2unix
    - gnuplot
    - PyXML
    - ImageMagick
    - libxslt-devel
    - libxml2-devel
    - libxml2-devel
    - ncurses-devel
    - libtiff-devel
    - perl-XML-LibXML
    - perl-XML-LibXML-Common
    - perl-XML-NamespaceSupport
    - perl-XML-SAX
    - perl-XML-Simple
    - perl-Archive-Zip
    - perl-CPAN
    - git

- name: install sisyphus dependencies from epel repository
  yum:
      name: "{{ item }}"
      state: present
      enablerepo: epel
  with_items:
    - perl-PDL
    - perl-PerlIO-gzip

- name: download cpanm
  get_url: url=http://cpanmin.us dest=/tmp/cpanm_install.pl

- name: install cpanm
  command: perl /tmp/cpanm_install.pl --sudo App::cpanminus

- name: install File::NFSLock
  cpanm: name=File::NFSLock

- name: create sisyphus code folder
  file: path={{ sisyphus_path }} state=directory

- name: get sisyphus code
  git: repo={{ sisyphus_git_repo }} version={{ sisyphus_repo_branch }} dest={{ sisyphus_path }}/sisyphus-tmp update=yes

- name: get sisyphus version
  command: git --git-dir={{ sisyphus_path }}/sisyphus-tmp/.git describe --tags
  register: sisyphus_version

- name: check if latest sisyphus version folder exists
  stat: path={{ sisyphus_path }}/sisyphus-{{ sisyphus_version.stdout }}
  register: latest_sisyphus_version_folder

- name: copy latest version to correct named folder
  command: cp -r {{ sisyphus_path }}/sisyphus-tmp {{ sisyphus_path }}/sisyphus-{{ sisyphus_version.stdout }}
  when: not latest_sisyphus_version_folder.stat.exists

- name: remove sisyphus-tmp
  file: path={{ sisyphus_path }}/sisyphus-tmp state=absent

- name: ensure latest version is globally readable
  file: state=directory path={{ sisyphus_path }}/sisyphus-{{ sisyphus_version.stdout }} mode=775 recurse=yes

- name: setup link to sisyphus latest
  file: state=link src={{ sisyphus_path }}/sisyphus-{{ sisyphus_version.stdout }} dest={{ sisyphus_path }}/sisyphus-latest mode=775

- name: set acl permissions on sisyphus code folder
  command: setfacl -R -m u:{{ arteria_user }}:rwx {{ sisyphus_path }}
